[project]
name = "arcticons-selfhosted"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "beautifulsoup4>=4.12.3",
    "cairosvg>=2.7.1",
    "jsonschema>=4.23.0",
    "pillow>=11.0.0",
]
