on:
  # on numbered tagged push and beta releases
  push:
    branches:
      - master
#    tags:
#      - '^\d+.\d.\d+(?:-beta)$'

jobs:
  build:
    name: Build Arcticons APK
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version" 