on:
  push:
    branches:
      - master
      - main
    paths:
      - icons/**
  workflow_dispatch:

jobs:
  Publish-Website:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Export icons to website
        run: |
          uv run scripts/publish-website.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git pull
          git add .
          git commit -m "Generated new website"
          git push       